import React from 'react';
import RegisterPageForm from './RegisterPageForm';
export const metadata = {
  title: "Register | StartupForge",
  description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <RegisterPageForm />
        </div>
    );
};

export default page;