import React, { Suspense } from 'react';
import RegisterPageForm from './RegisterPageForm';
export const metadata = {
    title: "Register | StartupForge",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <Suspense fallback={<div>Loading register form...</div>}>
            <RegisterPageForm />
        </Suspense>
    );
};

export default page;