import OpportunityFiltersContainer from '@/components/opportunities/OpportunityFiltersContainer';
import { getAllOpportunities } from '@/lib/api/opportunities';
import React from 'react';

export const metadata = {
  title: "Opportunities | StartupForge",
  description: "Generated by create next app",
};

const OpportunitiesPage = async ({ searchParams }) => {
    const filters = await searchParams;

    const querySearch = new URLSearchParams(filters)
    const queryString = querySearch.toString();
    console.log(queryString)

    const { opportunities , total} = await getAllOpportunities(queryString);
    console.log(opportunities, "from page");
    
    return (
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="my-10 text-center">
                <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-slate-900">
                    Discover Your Next Opportunity
                </h1>

                <p className="mt-4 max-w-2xl mx-auto text-base md:text-lg text-slate-600">
                    Explore exciting roles from innovative startups and growing teams.
                    Find the opportunity that matches your skills, goals, and passion.
                </p>
            </div>
            
            <OpportunityFiltersContainer opportunities={opportunities || []} total={total} filters={filters} />
        </div>
    );
};

export default OpportunitiesPage;