import React from 'react';
import ForbiddenPage from './ForbiddenPage';

const metadata = {
    title: "Forbidden | StartupForge",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <ForbiddenPage />
        </div>
    );
};

export default page;