import React from 'react';
import UnauthorizedPage from './UnauthorizedPage';

export const metadata = {
  title: "Unauthorized | StartupForge",
  description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <UnauthorizedPage />
        </div>
    );
};

export default page;