import React from 'react';
import LoginPageForm from './LoginPageForm';


export const metadata = {
  title: "Login | StartupForge",
  description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <LoginPageForm />
        </div>
    );
};

export default page;