import React, { Suspense } from 'react';
import LoginPageForm from './LoginPageForm';


export const metadata = {
    title: "Login | StartupForge",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <Suspense fallback={<div>Loading register form...</div>}>
            <LoginPageForm />
        </Suspense>
    );
};

export default page;