import StartupFiltersContainer from '@/components/startups/StartupsFiltersContainer';
import { getAllStartups } from '@/lib/api/startup';
import React from 'react';

export const metadata = {
  title: "Startups | StartupForge",
  description: "Generated by create next app",
};


const page = async ({ searchParams }) => {
    const filters = await searchParams;

    const querySearch = new URLSearchParams(filters)
    const queryString = querySearch.toString();

    const { startups, total } = await getAllStartups(queryString);



    return (
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
            {/* Header Info Section */}
            <div className="mb-10 border-b border-slate-100 pb-6 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                <div>
                    <h1 className="text-3xl font-bold text-slate-900 tracking-tight">
                        Explore Startups
                    </h1>
                    <p className="text-slate-500 mt-1 text-sm">
                        Discover active innovations and companies forging ahead.
                    </p>
                </div>

                {/* Counter Badge */}
                <span className="inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold bg-slate-100 text-slate-700 w-fit self-start sm:self-center">
                    {startups?.length} Active {startups?.length === 1 ? 'Company' : 'Companies'}
                </span>
            </div>

            <StartupFiltersContainer startups={startups} total={total} filters={filters} />

        </div>
    );
};

export default page;