import React from 'react';
import FounderPlans from './FounderPlans';

export const metadata = {
  title: "Plans | StartupForge",
  description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <FounderPlans />
        </div>
    );
};

export default page;